#pragma once

#include <array>
#include <string_view>

#include "config/enums.hpp"

namespace dl::config {

/// Ported from cheat/src/cs2/key_codes.rs. The numeric values match the rust enum, so the
/// two sides agree once the game layer starts reading these.
enum class KeyCode : int {
    None = 0,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Space,
    Backspace,
    Tab,
    Escape,
    Insert,
    Delete,
    Home,
    End,
    LeftShift,
    LeftAlt,
    LeftControl,
    MouseLeft,
    MouseRight,
    MouseMiddle,
    Mouse4,
    Mouse5,
    MouseWheelUp,
    MouseWheelDown,
};

inline constexpr std::array<EnumEntry<KeyCode>, 55> keycode_entries{{
    {KeyCode::None, "None", "none"},
    {KeyCode::Num0, "0", "num0"},
    {KeyCode::Num1, "1", "num1"},
    {KeyCode::Num2, "2", "num2"},
    {KeyCode::Num3, "3", "num3"},
    {KeyCode::Num4, "4", "num4"},
    {KeyCode::Num5, "5", "num5"},
    {KeyCode::Num6, "6", "num6"},
    {KeyCode::Num7, "7", "num7"},
    {KeyCode::Num8, "8", "num8"},
    {KeyCode::Num9, "9", "num9"},
    {KeyCode::A, "A", "a"},
    {KeyCode::B, "B", "b"},
    {KeyCode::C, "C", "c"},
    {KeyCode::D, "D", "d"},
    {KeyCode::E, "E", "e"},
    {KeyCode::F, "F", "f"},
    {KeyCode::G, "G", "g"},
    {KeyCode::H, "H", "h"},
    {KeyCode::I, "I", "i"},
    {KeyCode::J, "J", "j"},
    {KeyCode::K, "K", "k"},
    {KeyCode::L, "L", "l"},
    {KeyCode::M, "M", "m"},
    {KeyCode::N, "N", "n"},
    {KeyCode::O, "O", "o"},
    {KeyCode::P, "P", "p"},
    {KeyCode::Q, "Q", "q"},
    {KeyCode::R, "R", "r"},
    {KeyCode::S, "S", "s"},
    {KeyCode::T, "T", "t"},
    {KeyCode::U, "U", "u"},
    {KeyCode::V, "V", "v"},
    {KeyCode::W, "W", "w"},
    {KeyCode::X, "X", "x"},
    {KeyCode::Y, "Y", "y"},
    {KeyCode::Z, "Z", "z"},
    {KeyCode::Space, "Space", "space"},
    {KeyCode::Backspace, "Backspace", "backspace"},
    {KeyCode::Tab, "Tab", "tab"},
    {KeyCode::Escape, "Escape", "escape"},
    {KeyCode::Insert, "Insert", "insert"},
    {KeyCode::Delete, "Delete", "delete"},
    {KeyCode::Home, "Home", "home"},
    {KeyCode::End, "End", "end"},
    {KeyCode::LeftShift, "Left Shift", "left_shift"},
    {KeyCode::LeftAlt, "Left Alt", "left_alt"},
    {KeyCode::LeftControl, "Left Control", "left_control"},
    {KeyCode::MouseLeft, "Mouse Left", "mouse_left"},
    {KeyCode::MouseRight, "Mouse Right", "mouse_right"},
    {KeyCode::MouseMiddle, "Mouse Middle", "mouse_middle"},
    {KeyCode::Mouse4, "Mouse 4", "mouse4"},
    {KeyCode::Mouse5, "Mouse 5", "mouse5"},
    {KeyCode::MouseWheelUp, "Wheel Up", "mouse_wheel_up"},
    {KeyCode::MouseWheelDown, "Wheel Down", "mouse_wheel_down"},
}};

constexpr const auto& enum_entries(KeyCode) { return keycode_entries; }

/// The key or mouse button pressed this frame, or KeyCode::None when nothing was. Used by
/// the keybind widget while it is capturing.
KeyCode pressed_key();

}  // namespace dl::config
