#pragma once

#include <array>
#include <cstddef>
#include <utility>

#include "config/enums.hpp"

namespace dl::config {

/// Ported from shared/src/weapon.rs, declaration order preserved.
enum class Weapon : std::size_t {
    None,
    CZ75,
    DesertEagle,
    DualBerettas,
    FiveSeven,
    Glock,
    P2000,
    P250,
    Revolver,
    Tec9,
    Usp,
    MAC10,
    MP5,
    MP7,
    MP9,
    P90,
    Bizon,
    UMP45,
    Mag7,
    Nova,
    SawedOff,
    XM1014,
    M249,
    Negev,
    AK47,
    Aug,
    Famas,
    Galil,
    M4A1S,
    M4A4,
    SG553,
    Awp,
    G3SG1,
    SCAR20,
    SSG08,
    KnifeCT,
    KnifeT,
    KnifeBayonet,
    KnifeBowie,
    KnifeButterfly,
    KnifeClassic,
    KnifeFalchion,
    KnifeFlip,
    KnifeGut,
    KnifeHuntsman,
    KnifeKarambit,
    KnifeKukri,
    KnifeM9Bayonet,
    KnifeNavaja,
    KnifeNomad,
    KnifeParacord,
    KnifeShadowDaggers,
    KnifeSkeleton,
    KnifeStiletto,
    KnifeSurvival,
    KnifeTalon,
    KnifeUrsus,
    KnifeGold,
    Flashbang,
    HE,
    Smoke,
    Molotov,
    Decoy,
    Incendiary,
    Taser,
    C4,
    Healthshot,
};

inline constexpr std::size_t weapon_count = 67;

inline constexpr std::array<EnumEntry<Weapon>, weapon_count> weapon_entries{{
    {Weapon::None, "?", "none"},
    {Weapon::CZ75, "CZ75-Auto", "cz75"},
    {Weapon::DesertEagle, "Desert Eagle", "desert_eagle"},
    {Weapon::DualBerettas, "Dual Berettas", "dual_berettas"},
    {Weapon::FiveSeven, "Five-SeveN", "five_seven"},
    {Weapon::Glock, "Glock-18", "glock"},
    {Weapon::P2000, "P2000", "p2000"},
    {Weapon::P250, "P250", "p250"},
    {Weapon::Revolver, "R8 Revolver", "revolver"},
    {Weapon::Tec9, "Tec-9", "tec9"},
    {Weapon::Usp, "USP-S", "usp"},
    {Weapon::MAC10, "MAC-10", "mac10"},
    {Weapon::MP5, "MP5-SD", "mp5"},
    {Weapon::MP7, "MP7", "mp7"},
    {Weapon::MP9, "MP9", "mp9"},
    {Weapon::P90, "P90", "p90"},
    {Weapon::Bizon, "PP-Bizon", "bizon"},
    {Weapon::UMP45, "UMP-45", "ump45"},
    {Weapon::Mag7, "Mag-7", "mag7"},
    {Weapon::Nova, "Nova", "nova"},
    {Weapon::SawedOff, "Sawed-Off", "sawed_off"},
    {Weapon::XM1014, "XM1014", "xm1014"},
    {Weapon::M249, "M249", "m249"},
    {Weapon::Negev, "Negev", "negev"},
    {Weapon::AK47, "AK-47", "ak47"},
    {Weapon::Aug, "AUG", "aug"},
    {Weapon::Famas, "FAMAS", "famas"},
    {Weapon::Galil, "Galil AR", "galil"},
    {Weapon::M4A1S, "M4A1-S", "m4_a1_s"},
    {Weapon::M4A4, "M4A4", "m4_a4"},
    {Weapon::SG553, "SG 553", "sg553"},
    {Weapon::Awp, "AWP", "awp"},
    {Weapon::G3SG1, "G3SG1", "g3_sg1"},
    {Weapon::SCAR20, "SCAR-20", "scar20"},
    {Weapon::SSG08, "SSG 08", "ssg08"},
    {Weapon::KnifeCT, "Knife", "knife_ct"},
    {Weapon::KnifeT, "Knife", "knife_t"},
    {Weapon::KnifeBayonet, "Bayonet", "knife_bayonet"},
    {Weapon::KnifeBowie, "Bowie Knife", "knife_bowie"},
    {Weapon::KnifeButterfly, "Butterfly Knife", "knife_butterfly"},
    {Weapon::KnifeClassic, "Classic Knife", "knife_classic"},
    {Weapon::KnifeFalchion, "Falchion Knife", "knife_falchion"},
    {Weapon::KnifeFlip, "Flip Knife", "knife_flip"},
    {Weapon::KnifeGut, "Gut Knife", "knife_gut"},
    {Weapon::KnifeHuntsman, "Huntsman Knife", "knife_huntsman"},
    {Weapon::KnifeKarambit, "Karambit", "knife_karambit"},
    {Weapon::KnifeKukri, "Kukri Knife", "knife_kukri"},
    {Weapon::KnifeM9Bayonet, "M9 Bayonet", "knife_m9_bayonet"},
    {Weapon::KnifeNavaja, "Navaja Knife", "knife_navaja"},
    {Weapon::KnifeNomad, "Nomad Knife", "knife_nomad"},
    {Weapon::KnifeParacord, "Paracord Knife", "knife_paracord"},
    {Weapon::KnifeShadowDaggers, "Shadow Daggers", "knife_shadow_daggers"},
    {Weapon::KnifeSkeleton, "Skeleton Knife", "knife_skeleton"},
    {Weapon::KnifeStiletto, "Stiletto Knife", "knife_stiletto"},
    {Weapon::KnifeSurvival, "Survival Knife", "knife_survival"},
    {Weapon::KnifeTalon, "Talon Knife", "knife_talon"},
    {Weapon::KnifeUrsus, "Ursus Knife", "knife_ursus"},
    {Weapon::KnifeGold, "Gold Knife", "knife_gold"},
    {Weapon::Flashbang, "Flashbang", "flashbang"},
    {Weapon::HE, "HE Grenade", "he"},
    {Weapon::Smoke, "Smoke Grenade", "smoke"},
    {Weapon::Molotov, "Molotov", "molotov"},
    {Weapon::Decoy, "Decoy Grenade", "decoy"},
    {Weapon::Incendiary, "Incendiary Grenade", "incendiary"},
    {Weapon::Taser, "Zeus x27", "taser"},
    {Weapon::C4, "C4", "c4"},
    {Weapon::Healthshot, "Healthshot", "healthshot"},
}};
constexpr const auto& enum_entries(Weapon) { return weapon_entries; }

/// Ported from shared/src/bones.rs. The values are the game's bone indices, so the gaps
/// in the numbering are deliberate.
enum class Bones : int {
    Hip = 1,
    Spine1 = 2,
    Spine2 = 3,
    Spine3 = 4,
    Spine4 = 5,
    Neck = 6,
    Head = 7,
    LeftShoulder = 9,
    LeftElbow = 10,
    LeftHand = 11,
    RightShoulder = 13,
    RightElbow = 14,
    RightHand = 15,
    LeftHip = 17,
    LeftKnee = 18,
    LeftFoot = 19,
    RightHip = 20,
    RightKnee = 21,
    RightFoot = 22,
};

inline constexpr std::size_t bone_count = 19;

inline constexpr std::array<EnumEntry<Bones>, bone_count> bone_entries{{
    {Bones::Hip, "Hip", "hip"},
    {Bones::Spine1, "Spine1", "spine1"},
    {Bones::Spine2, "Spine2", "spine2"},
    {Bones::Spine3, "Spine3", "spine3"},
    {Bones::Spine4, "Spine4", "spine4"},
    {Bones::Neck, "Neck", "neck"},
    {Bones::Head, "Head", "head"},
    {Bones::LeftShoulder, "Left Shoulder", "left_shoulder"},
    {Bones::LeftElbow, "Left Elbow", "left_elbow"},
    {Bones::LeftHand, "Left Hand", "left_hand"},
    {Bones::RightShoulder, "Right Shoulder", "right_shoulder"},
    {Bones::RightElbow, "Right Elbow", "right_elbow"},
    {Bones::RightHand, "Right Hand", "right_hand"},
    {Bones::LeftHip, "Left Hip", "left_hip"},
    {Bones::LeftKnee, "Left Knee", "left_knee"},
    {Bones::LeftFoot, "Left Foot", "left_foot"},
    {Bones::RightHip, "Right Hip", "right_hip"},
    {Bones::RightKnee, "Right Knee", "right_knee"},
    {Bones::RightFoot, "Right Foot", "right_foot"},
}};
constexpr const auto& enum_entries(Bones) { return bone_entries; }

/// Which bones the skeleton is drawn between. Ported from shared/src/bones.rs.
inline constexpr std::array<std::pair<Bones, Bones>, 18> bone_connections{{
    // spine
    {Bones::Hip, Bones::Spine1},
    {Bones::Spine1, Bones::Spine2},
    {Bones::Spine2, Bones::Spine3},
    {Bones::Spine3, Bones::Spine4},
    {Bones::Spine4, Bones::Neck},
    {Bones::Neck, Bones::Head},
    // left arm
    {Bones::Neck, Bones::LeftShoulder},
    {Bones::LeftShoulder, Bones::LeftElbow},
    {Bones::LeftElbow, Bones::LeftHand},
    // right arm
    {Bones::Neck, Bones::RightShoulder},
    {Bones::RightShoulder, Bones::RightElbow},
    {Bones::RightElbow, Bones::RightHand},
    // left leg
    {Bones::Hip, Bones::LeftHip},
    {Bones::LeftHip, Bones::LeftKnee},
    {Bones::LeftKnee, Bones::LeftFoot},
    // right leg
    {Bones::Hip, Bones::RightHip},
    {Bones::RightHip, Bones::RightKnee},
    {Bones::RightKnee, Bones::RightFoot},
}};

}  // namespace dl::config
